require:
    - 'ts-node/register'
    - 'tsconfig-paths/register'
    - 'spec/root-hooks.ts'
recursive: true
extension:
    - 'ts'
    - 'js'
    - 'tsx'
spec:
    - 'spec/**/*.spec.ts'
timeout: '20000'
